[package]
name = "bsc"
version = "0.1.1"
authors = ["Maxime Tricoire <max.tricoire@gmail.com>"]
edition = "2018"
description = "Yet another tiny beanstalkd CLI"
license = "MIT"

[dependencies]
clap = "2.33.3"
beanstalkc = "0.2.9"