[package]
name = "bsc-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bsc"
path = "src/main.rs"

[dependencies]
bsc = { version = "0.1.0", path = "../lib" }
clap = { version = "4.1.6", features = ["derive", "env", "wrap_help"] }
eyre = "0.6.8"
serde_json = "1.0.93"
simple-eyre = "0.3.1"
